name: Video Compression Worker
on:
  repository_dispatch:
    types: [start_compress]

jobs:
  compress_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.9' }

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Install Dependencies
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
          sudo apt-get update
          sudo apt-get install -y --fix-missing ffmpeg

      - name: Run Compressor
        env:
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
        run: python compress.py ${{ github.event.client_payload.file_id }}
